### ISSUE TITLE
Stereo ORB-SLAM2 osmap

### ISSUE THREAD

**Issue by Shashika007** [AlejandroSilvestri/osmap#10]
Hi @AlejandroSilvestri , 

Great work! I have already integrated this to my orb-slam2 without any bugs. I am really interest to implement this to stereo version of orb-slam2. Could you give me some hints to follow what kind of extra parameters that i need to serialize and some brief procedure ? 

Thank you,

Shashika

**Comment by AlejandroSilvestri** [comment]
@Shashika007 ,

I believe you only need to serialize this two properties from KeyFrames:

- mvuRight
- mvDepth

The first to stereo, the second to RGBD.  They should be serialized in the "features" file, so you can add two floats to [ SerializedFeature in proto file](https://github.com/AlejandroSilvestri/osmap/blob/e7892640c128d3acaad3fcdaabf3d89b1233ddb9/osmap.proto#L97), like this:

```
message SerializedFeature{
  uint32 mappoint_id              = 2;  // mappoint id used to construct mvpMapPoints
  SerializedKeypoint keypoint     = 3;  // element of mvKeysUn
  SerializedDescriptor briefdescriptor = 4;  // row of mDescriptors.  This field is named briefdescriptor instead of descriptor because the latter es a reserved word in protocol buffers.
  float uRight = 5;
  float depth = 6;
}

```

Thinking about a general osmap compatible with monocular, stereo and RGBD, the main problem is that SerializedFeature is the most repeated object in file, and this addition adds 8 bytes to each feature, growing from 52+ bytes to 60+ bytes, about 15% of the total map files size, with no use in monocular.  I must find a trade off, maybe declaring both float as `repeated`.  But you can go with it, and maybe you don't even need depth.

You must modify [serialize](https://github.com/AlejandroSilvestri/osmap/blob/e7892640c128d3acaad3fcdaabf3d89b1233ddb9/src/Osmap.cpp#L947) and [deserialize](https://github.com/AlejandroSilvestri/osmap/blob/e7892640c128d3acaad3fcdaabf3d89b1233ddb9/src/Osmap.cpp#L967) features, and you would wanto to delete this lines [here](https://github.com/AlejandroSilvestri/osmap/blob/e7892640c128d3acaad3fcdaabf3d89b1233ddb9/src/Osmap.cpp#L979).

Maybe you'll have some problems in rebuild() after deserializing.  If so, let me know.

**Comment by tommyhannan** [comment]
@Shashika007 @AlejandroSilvestri Has any progress been made on stereo osmap? Thanks!

**Comment by Shashika007** [comment]
@AlejandroSilvestri  Thank you for your guidance. @tommyhannan Currently, i am working on it. I already serialize those two parameters successfully. I got some issues when i was deserialize the parameters.

**Comment by tommyhannan** [comment]
@Shashika007 Great, I'd really appreciate if you could share it once it's working
