### ISSUE TITLE
`Frame::mnId` is being repeated while mapping on loaded map (`Frame::nNextId` is not updated)

### ISSUE THREAD

**Issue by mmajewsk** [AlejandroSilvestri/osmap#12]
So the `KeyFrame::mnId` is updated, but `Frame::mnId` may repeat in new frames.
I suggest updating `Frame::nNextId` same way as here https://github.com/AlejandroSilvestri/osmap/blob/master/src/Osmap.cpp#L595

**Comment by AlejandroSilvestri** [comment]
@mmajewsk 

Thank you.  You are right.

Frame::mnId has no use in ORB-SLAM2, so it doesn't affect functionality, but anyone who are actually using Frame::mnId for a specific reason with modified code should apply this patch.
