### ISSUE TITLE
When loading map the library changes directory to the map location

### ISSUE THREAD

**Issue by Alexandre34** [AlejandroSilvestri/osmap#14]
Hello,
I had an issue when loading maps that are not in the same folder as the program.

Here is the deal : I have a folder containing all my maps (the yaml files and features) that is in **Data/Saved_maps**.
I have my recordings that are in separate folders (containing the rgb folder and frames) in **Data**.

My script first loads a map then loads a recording that contains frames for localizing in the map. When the map is not in the same folder as the script, the program loads successfully the map but crashes when trying to load the first frame.
`Failed to load image at: Data/loc_video/rgbVideo/339.png`
After searching in the mapLoad function I found that here the directory is changed if the map is not in the same folder.
https://github.com/AlejandroSilvestri/osmap/blob/e7892640c128d3acaad3fcdaabf3d89b1233ddb9/src/Osmap.cpp#L247

Which is fine, but it doesn't come back to the original directory of the script. For maps saved in the same directory it is fine, but for other cases the links are broken.

In order to solve that I suggest adding a call that comes back to the original location of the map after the map is loaded.
For example by adding the following just before the chdir.
```
// Get current directory
char currentDir[256];
getcwd(currentDir, sizeof(currentDir));
```
Then adding this at the end of the function.
```
// Goes back to the original directory when loading is complete
chdir(currentDir);
```

What do you think about this?
Thanks

**Comment by AlejandroSilvestri** [comment]
@Alexandre34 

Yes, you are right, thank you for pointing it out.

Osmap is intended to save and load the map, to define an extensible and flexible file format.  This issue is more related to the user interface, how the user tells the system where to load the map from.  It's quick and dirty code, I won't mess with it because it may stop working.  Any implementation of osmap should review suck things.
