### ISSUE TITLE
Protoc "PROTOBUF_DEPRECATED" error

### ISSUE THREAD

**Issue by mmajewsk** [AlejandroSilvestri/osmap#7]
Hi, thanks for sharing this project, I have been long looking for this.
I have a problem with compilation using the ORB_SLAM CMake, I did exactly what it said in readme, yet I have following error.
Can you help?

> In file included from /home/mwm/repositories/ORB_SLAM2/include/osmap.pb.h:36:0,
                 from /home/mwm/repositories/ORB_SLAM2/src/osmap.pb.cc:4:
/usr/local/include/google/protobuf/port_def.inc:74:2: error: #error PROTOBUF_DEPRECATED was previously defined
 #error PROTOBUF_DEPRECATED was previously defined
  ^~~~~
In file included from /home/mwm/repositories/ORB_SLAM2/include/osmap.pb.h:36:0,
                 from /home/mwm/repositories/ORB_SLAM2/include/Osmap.h:30,
                 from /home/mwm/repositories/ORB_SLAM2/src/Osmap.cpp:28:
/usr/local/include/google/protobuf/port_def.inc:74:2: error: #error PROTOBUF_DEPRECATED was previously defined
 #error PROTOBUF_DEPRECATED was previously defined
  ^~~~~
In file included from /home/mwm/repositories/ORB_SLAM2/src/osmap.pb.cc:4:0:
/home/mwm/repositories/ORB_SLAM2/include/osmap.pb.h:56:49: error: ‘DescriptorTable’ in namespace ‘google::protobuf::internal’ does not name a type
 extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_osmap_2eproto;

**Comment by AlejandroSilvestri** [comment]
@mmajewsk ,

Some users reported errors with protocol buffers, all of them discovered a problem with their protocol buffers installation.

Please tell me the version of protocol buffers cmake got, something like this:

    -- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.6.1") 

and the version protoc says in a terminal:

    $ protoc --version
    libprotoc 3.6.1

I believe actual version is 3.8.0.  The important thing is that protoc, the command you used to create two code files, uses the same version of the library cmake finds.  Tell me what protoc and cmake tell you.

[This issue](https://github.com/AlejandroSilvestri/osmap/issues/6) is the last conflicting version issue, @Alexandre34 fixed it by telling cmake the full path to get libprotobuf.so with the right version.  Other users cleaned their system leaving only one updated version of Protocol Buffers.

By the way, I updated readme.md this morning, I believe you already read the updated one, but I tell you just in case.

**Comment by Alexandre34** [comment]
Hi @mmajewsk 
Have you found a way to solve your problem?
I'm still experimenting with the CMake file and I would like to know if my modifications works on other systems than mine.
Thanks

**Comment by mmajewsk** [comment]
@AlejandroSilvestri @Alexandre34  
I managed to do pass through this problem, by **uninstalling anaconda** which i used at first to install this protobuff. At first I searched for any sign of libprotobuff and simmilar and tried to delete, but it was saying that there is no libprotobuff or others there. But encountered another during the run of the modified ORB_SLAM2 example which said:

```
This program requires version 3.8.0 of the Protocol Buffer runtime library
```

You are right, this is a proble mof previous installations, but having it "easy way" is tempting.
I suggest to strongly encourage everyone in readme to build protobuff from source, since this thing is hard to get rid off when you install wrong version.

**Comment by mmajewsk** [comment]
To be exact the the error is:
```
[libprotobuf FATAL google/protobuf/stubs/common.cc:68] This program requires version 3.8.0 of the Protocol Buffer runtime library, but the installed version is 3.5.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/any.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.8.0 of the Protocol Buffer runtime library, but the installed version is 3.5.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/any.pb.cc".)
Aborted (core dumped)
```

But the CMake says:
```
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.8.0") 
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread;-lpthread (found suitable version "3.8.0", minimum required is "3.8.0") 
```

**Comment by Alexandre34** [comment]
Hi @mmajewsk 
Have you regenerated **osmap.pb.cc** and **osmap.pb.h** after reinstalling the librairies?
Maybe they were generated with an older version of protoc.

As stated before, protoc and protobuf have to be the same version, but if you install everything from source they "should" have the same version.
Thanks

**Comment by AlejandroSilvestri** [comment]
@mmajewsk 

Please tell me the version protoc says in a terminal:

    $ protoc --version
    libprotoc 3.6.1

You must generate osmap.pb.cc and osmap.pb.h with protoc version 3.8.0.

But there's more.  CMake has correctly located protobuf runtime library version 3.8.0, but when you run the application, ld linux command is the one the system calls to load the libraries.  I believe ld is getting the wrong protobuf version.  In terminal:

    $ ldconfig -p | grep libprotobuf.so$

It will print the paths to all installations of this library ld will consider.  (You can remove the last $ to get more variants.)  Please paste the output here.

**Comment by mmajewsk** [comment]
Thank you all for your help, I decided to go the easy way, and just installed protobuf 3.5.1.
I will confirm that now it works and close the issue, but I still have some opencv problems to solve now.

**Comment by mmajewsk** [comment]
It does work now.
