### ISSUE TITLE
New map points are keyframes are not added after a map has been loaded

### ISSUE THREAD

**Issue by mmohmpat** [AlejandroSilvestri/osmap#9]
Hi there,

I have managed to save and load a map using the code, however, after the saved points and keyframes have been loaded, new map points and new keyframes are not added to the map. Is there a way to fix this?

Thanks :)

**Comment by AlejandroSilvestri** [comment]
Hi, after loading a map ORB-SLAM2 go to relocalization mode, and "only tracking" mode, also known as "localization" mode.

To continue building your map, you must push Localization mode button on ORB-SLAM2 viewer.
